# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20161002_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(to='team.Team'),
        ),
    ]
