# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20160816_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Hourly Rate'),
        ),
    ]
